spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  typeAliasesPackage: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/DeptMapper.xml

spring:
  profiles：dev
  application:
     name: microservicecloud-config-dept-client                         #很重要，这个就是对外暴露的名字
  datasource:
    url: jdbc:mysql://localhost:3306/cloudb03?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  dbcp2:
#     min-idle: 5
     initial-size: 5
     max-total: 5
     max-wait-millies: 200

     #以下为新增
     druid:
       # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
       #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
       test-on-borrow: false
       # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
       #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
       test-while-idle: true
       # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
       #validationQuery参数必须设置为非空字符串
       test-on-return: false
       # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
       #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
       validation-query: select 1

eureka:
  client:  #客户端注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版的
  instance:
    instance-id: dept-8001.com    #这个是修改eureka 服务注册的时候Status 下面的服务名字的
    prefer-ip-address: true  #这个是修改eureka的微服务被鼠标放上之后左下角显示的时候显示自己的ip

info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---