spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向服务中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检查服务
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/  #设置与Eureka Server 交互的地址查询服务和注册服务 (单机版的)
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向服务中心注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检查服务
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/      #设置与Eureka Server 交互的地址查询服务和注册服务 (单机版的)